### ISSUE TITLE
luci网络接口设置pppoe时不能选桥接

### ISSUE THREAD

**Issue by jsenetkx** [fanck0605/openwrt-nanopi-r2s#1]
双线接入  wan经过交换机设了vlan
r2s的luci载网络接口时pppoe下不能选桥接

暂时手动修改/etc/config/network 正常使用

**Comment by fanck0605** [comment]
应该是 lean 的 luci 的 bug 吧。我可能也解决不了。

**Comment by jsenetkx** [comment]
master没有这个问题
但是master opkg安装软件包装不了 要强制用--nodeps才行 不知道怎么解决

**Comment by fanck0605** [comment]
@jsenetkx 请使用最新原版 OpenWrt 编译的固件，应该没有这个问题了，
